[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-0001
upload_speed = 115200
board_build.partitions = no_ota.csv

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE=1
    -D LV_LVGL_H_INCLUDE_SIMPLE=1
    -D ST7789_DRIVER=1            ; Change from ILI9341_DRIVER
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=4                    
    -D TFT_BL=21
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_FONT6=1
    -D LOAD_FONT7=1
    -D LOAD_FONT8=1
    -D LOAD_GFXFF=1
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=20000000       ; Lowered slightly for stability
    -D SPI_READ_FREQUENCY=20000000
    -D SPI_TOUCH_FREQUENCY=2500000  ; Touch SPI must be much slower
    ; Touch Pins (Required for XPT2046)
    -D TOUCH_CS=33

lib_deps =
    lvgl/lvgl@^8.4
    bodmer/TFT_eSPI@^2.5.43
    https://gitea.sh3d.com.au/Sh3d/VictronBLE.git