// Generated by PicoPixel.io — https://picopixel.io
#include "actions.h"
#include "screens.h"
#include "ui.h"

// Animation timeline helpers
void pp_anim_stop_timelines_for_deleted_tree(lv_obj_t * root) {
    (void)root;
}


// Event callback implementations

// Event callback for solar_display on value-changed
void solar_display_value-changed_cb(lv_event_t * e) {
    /* Export warning: unresolved set-text target */
}

