// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_FONTS_H
#define PICOPIXEL_LVGL_UI_FONTS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Custom font declarations (externally visible const structs, no init needed) */
extern const lv_font_t font_f885947061f3803d8008276475c22ce3;
extern const lv_font_t font_f885947061f3803d8008276894e81300;
extern const lv_font_t font_f885947061f3803d800827698f876eb1;
extern const lv_font_t font_f885947061f3803d8008276d49550933;
extern const lv_font_t font_f885947061f3803d80082776dbb5ffeb;

/* Get a custom font by name, returns NULL if not found */
const lv_font_t* ui_get_font_by_name(const char* name);

#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_FONTS_H*/
