// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_EVENTS_H
#define PICOPIXEL_LVGL_UI_EVENTS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif


void pp_anim_stop_timelines_for_deleted_tree(lv_obj_t * root);

#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_EVENTS_H*/
