// Generated by PicoPixel.io — https://picopixel.io
#include "images.h"

#include "images/icon_power_lightning_empty.c"
#include "images/icon_loads.c"
#include "images/icon_temp.c"
#include "images/icon_sun.c"
#include "images/icon_victron.c"
const ext_img_desc_t images[5] = {
    { "icon_power_lightning_empty", &icon_power_lightning_empty },
    { "icon_loads", &icon_loads },
    { "icon_temp", &icon_temp },
    { "icon_sun", &icon_sun },
    { "icon_victron", &icon_victron }
};
