/*******************************************************************************
 * LVGL Victron BLE Dashboard (STABLE / FIXED)
 ******************************************************************************/

#include <lvgl.h>
#include <TFT_eSPI.h>
#include <VictronBLE.h>
#include "secrets.h"

#include "ui.h"
#include "vars.h"
#include "screens.h"

#include <esp_timer.h>

/* ---------------- DISPLAY ---------------- */
TFT_eSPI tft;

/* ---------------- VICTRON ---------------- */
VictronBLE victron;

/* ---------------- STATE ---------------- */
portMUX_TYPE victronMux = portMUX_INITIALIZER_UNLOCKED;

struct VictronSharedState {
    // SmartShunt Metrics
    float voltage;
    float current;
    float soc;
    int32_t remainingMinutes;

    // MPPT Metrics
    float solarVolts;
    float solarAmps;
    float power;
    uint8_t mpptState;

    // Diagnostics
    uint32_t shuntPackets;
    uint32_t mpptPackets;
    bool dataReady;
};

VictronSharedState sharedMetrics = {0};

/* ---------------- SYSTEM FLAGS ---------------- */
static bool uiReady = false;
static bool lvglReady = false;

/* ---------------- LVGL TICK ---------------- */
static void lv_tick_task(void *arg) {
    lv_tick_inc(1);
}

/* ---------------- DISPLAY FLUSH ---------------- */
void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p) {
    uint32_t w = area->x2 - area->x1 + 1;
    uint32_t h = area->y2 - area->y1 + 1;

    tft.startWrite();
    tft.setAddrWindow(area->x1, area->y1, w, h);
    tft.pushColors((uint16_t *)color_p, w * h, true); // True handles the byte swap cleanly here
    tft.endWrite();

    lv_disp_flush_ready(disp);
}

/* ---------------- SAFE UI UPDATE ---------------- */
void updateUI(const VictronSharedState& s) {

    if (!uiReady || !lvglReady) return;

    char buf[32];

    /* ---------------- SMARTSHUNT DATA ---------------- */
    if (objects.loadsvoltsdata) {
        snprintf(buf, sizeof(buf), "%.2f V", (double)s.voltage);
        lv_label_set_text(objects.loadsvoltsdata, buf);
    }

    if (objects.loadsampsdata) {
        snprintf(buf, sizeof(buf), "%.2f A", (double)s.current);
        lv_label_set_text(objects.loadsampsdata, buf);
    }

    if (objects.batterypercentdata) {
        snprintf(buf, sizeof(buf), "%d%%", (int)s.soc);
        lv_label_set_text(objects.batterypercentdata, buf);
    }

    if (objects.battery_bar) {
        lv_bar_set_value(objects.battery_bar, (int)s.soc, LV_ANIM_ON);
    }

    /* ---------------- SOLAR MPPT DATA ---------------- */
    if (objects.solarvoltsdata) {
        snprintf(buf, sizeof(buf), "%.2f V", (double)s.solarVolts);
        lv_label_set_text(objects.solarvoltsdata, buf);
    }

    if (objects.solarampsdata) {
        snprintf(buf, sizeof(buf), "%.2f A", (double)s.solarAmps);
        lv_label_set_text(objects.solarampsdata, buf);
    }

    if (objects.totalcharge) {
        snprintf(buf, sizeof(buf), "%d W", (int)s.power);
        lv_label_set_text(objects.totalcharge, buf);
    }

    if (objects.chargetypedata) {
        lv_label_set_text(objects.chargetypedata,
            (s.mpptState == 0) ? "OFF" : "ACTIVE");
    }
}

/* ---------------- BLE CALLBACK ---------------- */
void onVictronBleData(const VictronDevice* device) {

    if (!device->dataValid) return;

    portENTER_CRITICAL(&victronMux);

    if (device->deviceType == DEVICE_TYPE_BATTERY_MONITOR) {
        sharedMetrics.voltage = device->battery.voltage;
        sharedMetrics.current = device->battery.current;
        sharedMetrics.soc     = device->battery.soc;
        sharedMetrics.remainingMinutes = device->battery.remainingMinutes;
        sharedMetrics.shuntPackets++;
    }

    if (device->deviceType == DEVICE_TYPE_SOLAR_CHARGER) {
        sharedMetrics.power      = device->solar.panelPower;
        sharedMetrics.solarVolts = device->solar.batteryVoltage;
        sharedMetrics.solarAmps  = device->solar.batteryCurrent;
        sharedMetrics.mpptState  = device->solar.chargeState;
        sharedMetrics.mpptPackets++;
    }

    sharedMetrics.dataReady = true;

    portEXIT_CRITICAL(&victronMux);
}

/* ---------------- INIT LVGL ---------------- */
void initLVGL() {
    lv_init();

    // Use a standard landscape buffer block
    static lv_color_t buf[320 * 40] __attribute__((aligned(32)));
    static lv_disp_draw_buf_t draw_buf;
    lv_disp_draw_buf_init(&draw_buf, buf, NULL, 320 * 40);

    static lv_disp_drv_t disp_drv;
    lv_disp_drv_init(&disp_drv);

    // Hardcode to match the 320x240 layout generated by PicoPixel
    disp_drv.hor_res = 320; 
    disp_drv.ver_res = 240; 
    disp_drv.flush_cb = my_disp_flush;
    disp_drv.draw_buf = &draw_buf;

    lv_disp_drv_register(&disp_drv);
    lvglReady = true;
}

/* ---------------- SETUP ---------------- */
void setup() {

    Serial.begin(115200);
    delay(300);

    /* BACKLIGHT */
    pinMode(21, OUTPUT);
    digitalWrite(21, HIGH);

    /* TFT INIT */
    tft.init();
    tft.setRotation(0);
    tft.fillScreen(TFT_BLACK);
    tft.setSwapBytes(true);

    /* LVGL */
    initLVGL();

    /* LVGL TICK TIMER (CRITICAL) */
    const esp_timer_create_args_t tick_timer_args = {
        .callback = &lv_tick_task,
        .name = "lv_tick"
    };

    esp_timer_handle_t tick_timer;
    esp_timer_create(&tick_timer_args, &tick_timer);
    esp_timer_start_periodic(tick_timer, 1000);

    /* UI MUST BE AFTER LVGL */
    ui_init();
    uiReady = true;

    /* BLE */
    victron.addDevice("SmartShunt", SmartShuntMAC, SmartShuntEncryptionKey);
    victron.addDevice("SmartMPPT", SmartMPPTMAC, SmartMPPTEncryptionKey);
    victron.setCallback(onVictronBleData);
    victron.begin();

    Serial.println("SYSTEM READY");
}

/* ---------------- LOOP ---------------- */
void loop() {

    if (!lvglReady) return;

    victron.loop();
    lv_timer_handler();

    static uint32_t lastUI = 0;

    if (millis() - lastUI > 1000) {

        VictronSharedState snap;

        portENTER_CRITICAL(&victronMux);
        snap = sharedMetrics;
        sharedMetrics.dataReady = false;
        portEXIT_CRITICAL(&victronMux);

        if (snap.dataReady) {
            updateUI(snap);
        }

        lastUI = millis();
    }
}