// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_SCREENS_H
#define PICOPIXEL_LVGL_UI_SCREENS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _objects_t {
    lv_obj_t *screen_1;
    lv_obj_t *solarvoltsdata;
    lv_obj_t *icon_loads;
    lv_obj_t *chargetypedata;
    lv_obj_t *totalcharge;
    lv_obj_t *loadscontainer;
    lv_obj_t *image_1;
    lv_obj_t *icon_temp;
    lv_obj_t *timeremainingdata;
    lv_obj_t *smartshuntlabel;
    lv_obj_t *solardatacontainer;
    lv_obj_t *mpptlabel;
    lv_obj_t *icon_sun;
    lv_obj_t *battery_bar;
    lv_obj_t *icon_victron;
    lv_obj_t *tempdata;
    lv_obj_t *batterypercentdata;
    lv_obj_t *loadsampsdata;
    lv_obj_t *loadsvoltsdata;
    lv_obj_t *solarampsdata;
} objects_t;

extern objects_t objects;

enum ScreensEnum {
    SCREEN_ID_SCREEN_1 = 1,
};

void create_screen_screen_1();
void tick_screen_screen_1();
void delete_screen_screen_1();

void tick_screen_by_id(enum ScreensEnum screenId);
void tick_screen(int screen_index);

void delete_screen_by_id(enum ScreensEnum screenId);

void create_screens();


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_SCREENS_H*/
