// Generated by PicoPixel.io — https://picopixel.io
#include <string.h>

#include "screens.h"
#include "images.h"
#include "fonts/fonts.h"
#include "actions.h"
#include "vars.h"
#include "styles.h"
#include "ui.h"

objects_t objects;
lv_obj_t *tick_value_change_obj;
uint32_t active_theme_index = 0;

void create_screen_screen_1() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen_1 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 320, 240);
    {
        lv_obj_t *parent_obj = obj;
        {
            // chargetypedata
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.chargetypedata = obj;
            lv_obj_set_pos(obj, 24, 200);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_7d2e5bb2e35f8000800837d08ca802bf, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(0xff406280), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "CHARGETYPE");
        }
        {
            // totalcharge
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.totalcharge = obj;
            lv_obj_set_pos(obj, 24, 173);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_7d2e5bb2e35f8000800837d08ca802bf, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "TOTALCHARGE");
        }
        {
            // loadscontainer
            lv_obj_t *obj = lv_obj_create(parent_obj);
            objects.loadscontainer = obj;
            lv_obj_set_pos(obj, 168, 44);
            lv_obj_set_size(obj, 127, 114);
            lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xff22c55e), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // icon_loads
                    lv_obj_t *obj = lv_img_create(parent_obj);
                    objects.icon_loads = obj;
                    lv_obj_set_pos(obj, 55, 5);
                    lv_obj_set_size(obj, 16, 18);
                    lv_img_set_src(obj, &icon_power_lightning_empty);
                    lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
                    lv_img_set_zoom(obj, 396);
                    lv_img_set_antialias(obj, true);
                }
                {
                    // smartshuntlabel
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.smartshuntlabel = obj;
                    lv_obj_set_pos(obj, 27, 29);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_7d2e5bb2e35f8000800837d08ca802bf, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "SMARTSHUNT");
                }
                {
                    // loadsampsdata
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.loadsampsdata = obj;
                    lv_obj_set_pos(obj, 17, 52);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_7d2e5bb2e35f8000800837d08ca802c0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff22c55e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "LoadsAmps");
                }
                {
                    // loadsvoltsdata
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.loadsvoltsdata = obj;
                    lv_obj_set_pos(obj, 12, 87);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_7d2e5bb2e35f8000800837d08ca802c0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff22c55e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "LoadsVolts");
                }
            }
        }
        {
            // image_1
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.image_1 = obj;
            lv_obj_set_pos(obj, 8, 8);
            lv_obj_set_size(obj, 19, 21);
            lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff1da1d0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_img_set_src(obj, &icon_loads);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_zoom(obj, 427);
            lv_img_set_antialias(obj, true);
        }
        {
            // icon_temp
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.icon_temp = obj;
            lv_obj_set_pos(obj, 280, 15);
            lv_obj_set_size(obj, 5, 11);
            lv_img_set_src(obj, &icon_temp);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // solardatacontainer
            lv_obj_t *obj = lv_obj_create(parent_obj);
            objects.solardatacontainer = obj;
            lv_obj_set_pos(obj, 22, 44);
            lv_obj_set_size(obj, 127, 114);
            lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xff1da1d0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // solarvoltsdata
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.solarvoltsdata = obj;
                    lv_obj_set_pos(obj, 12, 84);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_7d2e5bb2e35f8000800837d08ca802c0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff1da1d0), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "SolarVolts");
                }
                {
                    // mpptlabel
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.mpptlabel = obj;
                    lv_obj_set_pos(obj, 27, 29);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_7d2e5bb2e35f8000800837d08ca802bf, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "MPPT 75/15");
                }
                {
                    // icon_sun
                    lv_obj_t *obj = lv_img_create(parent_obj);
                    objects.icon_sun = obj;
                    lv_obj_set_pos(obj, 52, 4);
                    lv_obj_set_size(obj, 19, 19);
                    lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff1da1d0), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_img_recolor_opa(obj, LV_OPA_COVER, LV_PART_MAIN);
                    lv_img_set_src(obj, &icon_sun);
                    lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
                    lv_img_set_antialias(obj, true);
                }
                {
                    // solarampsdata
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.solarampsdata = obj;
                    lv_obj_set_pos(obj, 17, 48);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_7d2e5bb2e35f8000800837d08ca802c0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff1da1d0), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "SolarAmps");
                }
            }
        }
        {
            // battery_bar
            lv_obj_t *obj = lv_bar_create(parent_obj);
            objects.battery_bar = obj;
            lv_obj_set_pos(obj, 21, 170);
            lv_obj_set_size(obj, 274, 44);
            lv_bar_set_range(obj, 0, 100);
            lv_bar_set_value(obj, 50, LV_ANIM_OFF);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff406280), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff22c55e), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        {
            // timeremainingdata
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.timeremainingdata = obj;
            lv_obj_set_pos(obj, 24, 187);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_7d2e5bb2e35f8000800837d08ca802bf, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "TIME REMAINING");
        }
        {
            // icon_victron
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.icon_victron = obj;
            lv_obj_set_pos(obj, 32, 11);
            lv_obj_set_size(obj, 101, 15);
            lv_obj_set_style_transform_pivot_y(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_x(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff1da1d0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_angle(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 256, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_img_set_src(obj, &icon_victron);
            lv_img_set_antialias(obj, true);
        }
        {
            // tempdata
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.tempdata = obj;
            lv_obj_set_pos(obj, 288, 13);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_7d2e5bb2e35f8000800837d08ca802bf, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_x(obj, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_y(obj, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_angle(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "temp");
        }
        {
            // batterypercentdata
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.batterypercentdata = obj;
            lv_obj_set_pos(obj, 212, 175);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_7d2e5bb2e35f8000800837d08ca802c2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "...%");
        }
    }

    tick_screen_screen_1();
}

void tick_screen_screen_1() {
}



typedef void (*tick_screen_func_t)();
tick_screen_func_t tick_screen_funcs[] = {
    tick_screen_screen_1,
};
void tick_screen(int screen_index) {
    tick_screen_funcs[screen_index]();
}
void tick_screen_by_id(enum ScreensEnum screenId) {
    tick_screen_funcs[screenId - 1]();
}

void delete_screen_screen_1() {
    if (objects.screen_1 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen_1);
        lv_obj_del(objects.screen_1);
    }
    objects.screen_1 = 0;
    objects.chargetypedata = 0;
    objects.totalcharge = 0;
    objects.loadscontainer = 0;
    objects.icon_loads = 0;
    objects.smartshuntlabel = 0;
    objects.loadsampsdata = 0;
    objects.loadsvoltsdata = 0;
    objects.image_1 = 0;
    objects.icon_temp = 0;
    objects.timeremainingdata = 0;
    objects.solardatacontainer = 0;
    objects.solarvoltsdata = 0;
    objects.mpptlabel = 0;
    objects.icon_sun = 0;
    objects.solarampsdata = 0;
    objects.battery_bar = 0;
    objects.icon_victron = 0;
    objects.tempdata = 0;
    objects.batterypercentdata = 0;
}


typedef void (*delete_screen_func_t)();
delete_screen_func_t delete_screen_funcs[] = {
    delete_screen_screen_1,
};
void delete_screen_by_id(enum ScreensEnum screenId) {
    delete_screen_funcs[screenId - 1]();
}

void create_screens() {
    lv_disp_t *dispp = lv_disp_get_default();
    // Use dark theme (true) to match the editor's appearance - white text on dark buttons
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    create_screen_screen_1();
}
