// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_VARS_H
#define PICOPIXEL_LVGL_UI_VARS_H
#ifndef SCREEN_ID_MAIN
#define SCREEN_ID_MAIN SCREEN_ID_SCREEN_1
#endif

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

enum GlobalVariables {
    FLOW_GLOBAL_VARIABLE_NONE
};

// No variables defined


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_VARS_H*/
